{% set name = "llama-index-agent-openai" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/llama_index_agent_openai-{{ version }}.tar.gz
    sha256: debe86da6d9d983db32b445ddca7c798ac140fe59573bafded73595b3995f3d5
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core
    - pip
  run:
    - openai >=1.14.0
    - python >=3.8.1,<3.12
    - llama-index-core >=0.10.41,<0.11.0
    - llama-index-llms-openai >=0.1.5,<0.2.0

test:
  imports:
    - llama_index.agent.openai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://llamaindex.ai
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/agent/llama-index-agent-openai
  summary: llama-index agent openai integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pavelzw
